# Generate an order-1 linear ODE system

# The system is generated by following steps:

# 1. Generating a block-diagonal matrix,
# as the linear term of the system.
# Each block is a scalar "a",
# indicating a real eigen-value,
# or of form:
#     a b
#    -b a
# which indicates a pair of complex eigen-values: a+-bi
# The analytic solution is:
#     exp(at)
# for real eigen-value, and
#     exp(at)sin(bt)
#     exp(at)cos(bt)
# for a pair of complex eigen-values.
# Each "a" is generated independently and uniform-randomly in range:
#     [real_min,real_max].
# The negative "real_min" value satisfies that the magnitude at the last
# time point is approximately half of that at the first one.
# "real_max" is half of the lower-bound.
# Each "b" should be bounded away from each other
# to decrease correlation of the system.
# Currently they are chosen as an arithmetic sequence.
# The smallest "b" is chosen to contain approximately
# one period in the time span when no real eigen-value exists,
# and double that value when there exists one real eigen-value.
# The order of "b" is permuted to break the ascension.

# 2a. Scaling coefficients in the linear term to similar magnitude.
# Disables 2b.
# Only for case of even dimension,
# and magnitude of imaginary part of eigenvalues is much larger than
# real part.
# For each 2x2 diagonal block, a similarity transformation
#     a b
#     c 1
# is applied.
# The optimal a,b,c are computed via Levenberg-Marquardt algorithm.

# 2b. Use a series of similarity transformation via orthogonal matrices
# to mix adjacent diagonal blocks.
# Disables 2a.

generate.linear <- function (
  dimension
  , timepoint
  , scaling = FALSE
  , orthogonal_transformation = list()
  , sanitycheck = FALSE
)

# INPUT:
# dimension: Dimension of the system.
#   Currently the system can contain complex eigen-values,
#   which appear in pairs,
#   and at most one real eigen-value,
#   since currently we have not found a good way to control
#   the correlation between curves of real eigen-values.
#   Hence if "dimension" is even, all eigen-values are complex,
#   otherwise there exists one real eigen-value in the spectrum.
# timepoint: Time points for observation data curves.
# scaling: Scaling coefficients of linear term to similar magnitude.
#   Can only be applied for even dimension.
# sanitycheck: Whether to perform a sanity check on input arguments.

# OUTPUT:
# initial: Initial condition of the system.
# linear: Linear term of the system.
#   It will be identical to the first column of "curve".
# eigen_complex: Complex eigenvalues of the linear term.
#   Notice that the conjugate of each element is also an eigenvalue.
# eigen_real: Real eigenvalues of the linear term.
# data: Data matrix for value at given time points.
#   Each column stands for a curve.
#   First column is "timepoint".

{

ret <- list()

# Sanity check#{{{

if ( sanitycheck )
{

# dimension#{{{
  if (
    !is.integer(dimension)
    || length(dimension)!=1
    || dimension<=0
  )
  {
    stop('Argument "dimension" must be a positive integer.')
  }
#}}}

# timepoint#{{{
  if (
    !is.numeric(timepoint)
    || length(timepoint)<2
    || is.unsorted(timepoint,strictly=TRUE)
  )
  {
    stop('Argument "timepoint" must be a numeric vector ' ,
      'with strictly ascending elements.')
  }
#}}}

# scaling#{{{
  if (
    !is.logical(scaling)
    || length(scaling)!=1
  )
  {
    stop('Argument "scaling" must be a logical scalar.')
  }

  if (
    scaling
    && dimension%%2!=0
  )
  {
    stop('Argument "scaling" cannot be TRUE for an odd "dimension".')
  }
#}}}

# orthogonal_transformation#{{{
  if ( !is.list(orthogonal_transformation) )
  {
    stop('Argument "orthogonal_transformation" should be a list.')
  }
  if (
    scaling
    && length(orthogonal_transformation)!=0
  )
  {
    stop('Argument "orthogonal_transformation" can only be non-empty ',
      'when "scaling" is FALSE.')
  }
  for ( item in orthogonal_transformation )
  {
    if (
      !is.integer(item)
      || length(item)!=2
    )
    {
      stop('Each element of argument "orthogonal_transformation" '
        ,'must be an integer vector of length 2.')
    }
    if ( item[1]>=item[2] )
    {
      stop('In each element of argument "orthogonal_transformation", ' ,
        'the second component must be larger than first.'
      )
    }
    if ( item[1]<1 || item[2]>dimension )
    {
      stop('Out-of-bound index in elements of '
        ,'argument "orthogonal_transformation".')
    }
  }
#}}}

}
#}}}

# Generate eigenvalues#{{{

num_real_eigen <- dimension%%2
num_complex_eigen <- floor(dimension/2)

time_span <- tail(timepoint,1) - timepoint[1]

real_min = -0.7/time_span
real_max = real_min/2

eigen_real <- runif (
  num_complex_eigen + num_real_eigen
  , real_min
  , real_max
)
  eigen_real[] <- real_min


eigen_imaginary <- 1:num_complex_eigen
if ( num_real_eigen>0 )
{
  eigen_imaginary <- eigen_imaginary + 1
}
eigen_imaginary <- eigen_imaginary * 2 * pi / time_span

require('permute')
permute_index <- permute::shuffle(num_complex_eigen)
permute_index <- 1:num_complex_eigen
eigen_imaginary <- eigen_imaginary[permute_index]

ret$eigen_complex <-
  1i*eigen_imaginary + eigen_real[1:num_complex_eigen]
if ( num_real_eigen==1 )
{
  ret$eigen_real <- tail(eigen_real,1)
}
else
{
  ret$eigen_real <- numeric(0)
}
#}}}

# Linear term#{{{

temp <- (1:num_complex_eigen) * 2

ret$linear <- matrix ( 0 , dimension , dimension )

ret$linear [ cbind(temp,temp) ] <-
  eigen_real[1:num_complex_eigen]
ret$linear [ cbind(temp-1,temp-1) ] <-
  eigen_real[1:num_complex_eigen]
ret$linear [ cbind(temp-1,temp) ] <-
  eigen_imaginary
ret$linear [ cbind(temp,temp-1) ] <-
  -eigen_imaginary
#}}}

# Data#{{{
ret$data <- matrix ( 0 , length(timepoint) , dimension )

lapply ( 1 : num_complex_eigen ,
  function(index)
  {
    temp <- exp ( eigen_real[index] * timepoint )
    ret$data[,2*index-1] <<-
      temp * sin ( eigen_imaginary[index] * timepoint )
    ret$data[,2*index] <<-
      temp * cos ( eigen_imaginary[index] * timepoint )
    return()
  }
)
#}}}

# Real eigenvalue#{{{
if ( num_real_eigen == 1 )
{
  ret$linear[dimension,dimension] <- tail(eigen_real,1)
  ret$data[,dimension] <- exp ( tail(eigen_real,1) * timepoint )
}
#}}}

# Initial condition#{{{
ret$initial <- rep ( 1 , dimension )
ret$initial [ 2*(1:num_complex_eigen)-1 ] <- 0
#}}}

# Scaling#{{{
if ( scaling )
{
  objective <- function (
    par
    , k
  )
  {
    ret <- numeric(3)
    temp <- k * ( par[1] - par[2]*par[3] )
    ret[1] <- par[1]*par[3] + par[2] - temp
    ret[2] <- par[1]**2 + par[2]**2 - temp
    ret[3] <- par[3]**2 + 1 - temp
    return(ret)
  }

  jacobian <- function (
    par
    , k
  )
  {
    ret <- matrix ( 0 , 3 , 3 )
    ret[1] <- par[3] - k
    ret[2] <- 2*par[1] - k
    ret[3] <- -k
    ret[4] <- 1 + par[3]*k
    ret[5] <- 2*par[2] + par[3]*k
    ret[6] <- par[3]*k
    ret[7] <- par[1] + par[2]*k
    ret[8] <- par[2]*k
    ret[9] <- 2*par[3] + par[2]*k
    return(ret)
  }

  require('minpack.lm')
  lapply ( 1 : num_complex_eigen , function(index)
  {
    scale_mat <-
      nls.lm (
        rep ( 1 , 3 )
        , lower = numeric(3)
        , upper = NULL
        , fn = objective
        , jac = jacobian
        , control = nls.lm.control()
        , k = num_complex_eigen/permute_index[index]
      ) $ par
    scale_mat <- matrix ( c(scale_mat,1) , 2 , 2 )
    temp <- (2*index-1) : (2*index)
    ret$data[,temp] <<- ret$data[,temp] %*% scale_mat
    scale_mat <- t(scale_mat)
    ret$linear[temp,temp] <<-
      scale_mat %*% ret$linear[temp,temp] %*% solve(scale_mat)
    ret$initial[temp] <<- scale_mat %*% ret$initial[temp]
  } )
}
#}}}

# Orthogonal transformation#{{{
for ( item in orthogonal_transformation )
{
  require('pracma')
  temp <- diag(dimension)
  temp [ item[1]:item[2] , item[1]:item[2] ] <-
    pracma::rortho ( item[2]-item[1]+1 )
  ret$data <- ret$data %*% t(temp)
  ret$linear <- temp %*% ret$linear %*% t(temp)
  ret$initial <- temp %*% ret$initial
}
#}}}

ret$data <- cbind ( timepoint , ret$data )

return(ret)

}

# vim: set tw=72 fdm=marker: Modeline for Vim
